name: SEBAR Super Uploader
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'لینکی فیلمەکە'
        required: true
      mode:
        description: 'جۆری ئیشەکە'
        required: true
      audio_url:
        description: 'لینکی دەنگی دۆبلاژ (ئارەزوومەندانە)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install pyrogram tgcrypto yt-dlp requests
          
      - name: Run Uploader
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
          MODE: ${{ github.event.inputs.mode }}
          AUDIO_URL: ${{ github.event.inputs.audio_url }}
        run: python upload.py
